global:
  tlsDisable: true

server:
  dataStorage:
    size: 128Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      - hosts:
          - vault-127-0-0-1.nip.io
        secretName: tls-io-nip-wildcard
    hosts:
      - host: vault-127-0-0-1.nip.io
  volumes:
    - name: post-start-script
      configMap:
        name: vault-post-start-script
        defaultMode: 0777
  volumeMounts:
    - mountPath: /vault/userconfig
      name: post-start-script
  postStart:
    - /bin/sh
    - -c
    - /vault/userconfig/vault-post-start.sh
