version: '3'

tasks:
  dev-server:
    cmds:
      - >-
        npx ng serve --ssl \
          --ssl-cert ../../k8s/cluster/dev/.certs/_wildcard.nip.io.pem \
          --ssl-key ../../k8s/cluster/dev/.certs/_wildcard.nip.io-key.pem \
          --disable-host-check

  install:
    cmds:
      - npm install --prune
    sources:
      - package.json
    generates:
      - node_modules/**/*
  build:
    deps: [install]
    cmds:
      - npm run build
    sources:
      - .eslintrc.json
      - angular.json
      - tsconfig.json
      - projects/**/*
    generates:
      - dist/**/*
  test:
    deps: [install]
    cmds:
      - npm run test
  test-ci:
    deps: [install]
    cmds:
      - npm run test-ci
    sources:
      - projects/**/*
    generates:
      - reports/**/*

