site:
  title: Acme
  url: https://mattupstate.com/acme
  start_page: ROOT::index.adoc
  keys:
    google_analytics: UA-552135-7
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    page-component-order: '!ROOT, acme-handbook, acme-adr, *'
    # kroki-fetch-diagram: true
content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: https://github.com/mattupstate/acme.git
      branches: main
      start_paths: acme-docs/root, acme-docs/handbook, acme-docs/decisions, acme-web/acme-web-server/docs
ui:
  bundle:
    url: https://gitlab.com/mattupstate/acme-antora-ui/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
