apiVersion: skaffold/v1
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: acme/acme-web-server
      jib:
        project: "acme-web:acme-web-server"

    - image: acme/acme-app-web
      context: ./acme-app/acme-app-web
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'projects/**/*.*'
            dest: .
  local:
    push: false

deploy:
  kustomize:
    path: acme-ops/src/k8s/overlays/dev
