apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: mattupstate/acme-data-sql
      context: ./acme-data/acme-data-sql
    - image: mattupstate/acme-web-app
      jib:
        project: "acme-web:acme-web-app"
      sync:
        auto: true
  local:
    push: false

manifests:
  rawYaml:
    - skaffold.oathkeeper.rules.yaml
  helm:
    releases:
      - name: acme-data-sql
        chartPath: acme-helm-charts/acme-data-sql
        skipTests: true
      - name: acme-web-app
        chartPath: acme-helm-charts/acme-web-app
        skipTests: true
        valuesFiles:
          - skaffold.acme-web-app.yaml
