apiVersion: skaffold/v3
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: mattupstate/acme-data-sql
      context: ./acme-data/acme-data-sql
    - image: mattupstate/acme-web-server
      jib:
        project: "acme-web:acme-web-server"
    - image: mattupstate/acme-app-web
      context: ./acme-app/acme-app-web
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'projects/**/*.*'
            dest: .
  local:
    push: false

deploy:
  helm:
    releases:
      - name: acme-oathkeeper
        chartPath: vendor/ory-helm-charts/helm/charts/oathkeeper
        setFiles:
          accessRules: skaffold.access-rules.yaml
        valuesFiles:
          - skaffold.oathkeeper.yaml
      - name: acme-data-sql
        chartPath: acme-helm-charts/acme-data-sql
      - name: acme-web-server
        chartPath: acme-helm-charts/acme-web-server
        valuesFiles:
          - skaffold.acme-web-server.yaml
        setValues:
          podEnv[0].name: LOG_FORMAT
          podEnv[0].value: text
      - name: acme-app-web
        chartPath: acme-helm-charts/acme-app-web
        valuesFiles:
          - skaffold.acme-app-web.yaml

profiles:
  - name: with-ops-stack
    activation:
      - env: OPS_STACK_ENABLED=true
    patches:
      - op: replace
        path: /deploy/helm/releases/2/setValues/podEnv[0].value
        value: json

