apiVersion: skaffold/v3
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: acme/acme-data-sql
      context: ./acme-data/acme-data-sql
    - image: acme/acme-web-server
      jib:
        project: "acme-web:acme-web-server"
    - image: acme/acme-app-web
      context: ./acme-app/acme-app-web
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'projects/**/*.*'
            dest: .
  local:
    push: false

manifests:
  kustomize:
    paths:
      - acme-ops/src/k8s/overlays/dev

deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: [ "sh", "-c", "kubectl delete job liquibase || true" ]
