apiVersion: skaffold/v3
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: mattupstate/acme-data-sql
      context: ./acme-data/acme-data-sql
    - image: mattupstate/acme-web-server
      jib:
        project: "acme-web:acme-web-server"
  #    - image: mattupstate/acme-app-web
  #      context: ./acme-app/acme-app-web
  #      docker:
  #        dockerfile: Dockerfile
  #        target: dev
  #      sync:
  #        manual:
  #          - src: 'projects/**/*.*'
  #            dest: .
  local:
    push: false

deploy:
  helm:
    releases:
      - name: acme-oathkeeper
        chartPath: vendor/ory-helm-charts/helm/charts/oathkeeper
        setFiles:
          accessRules: skaffold.access-rules.yaml
        valuesFiles:
          - skaffold.oathkeeper.yaml
      - name: acme-data-sql
        chartPath: acme-data/acme-data-sql/helm/acme-data-sql
      - name: acme-web-server
        chartPath: acme-web/acme-web-server/helm/acme-web-server
#      - name: acme-app-web
#        chartPath: acme-app/acme-app-web/helm/acme-app-web
#      - name: acme-web-oathkeeper
#        chartPath: acme-web/acme-web-oathkeeper
