apiVersion: skaffold/v1
kind: Config
metadata:
  name: acme

build:
  artifacts:
    - image: acme/acme-web-server
      jib:
        project: "acme-web:acme-web-server"
#  local:
#    push: false

deploy:
  kustomize:
    path: acme-ops/src/k8s/overlays/dev

profiles:
  - name: local
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: acme/acme-app-web
          context: ./acme-app/acme-app-web
    deploy:
      kustomize:
        path: acme-ops/src/k8s/overlays/local

#  - name: prod
#    deploy:
#      kustomize:
#        paths:
#          path: acme-ops/src/k8s/overlays/prod
