deployment:
  port: 4200

ingress:
  enabled: true
  className: nginx
  tls:
    - hosts:
        - app-127-0-0-1.nip.io
      secretName: tls-io-nip-wildcard
  hosts:
    - host: app-127-0-0-1.nip.io
      paths:
        - path: "/"
          pathType: Prefix
