version: 3

includes:
  acme-app:acme-app-web: 
    taskfile: ./acme-app/acme-app-web/Taskfile.yaml
    dir: ./acme-app/acme-app-web/
  dev: 
    taskfile: ./k8s/cluster/dev/Taskfile.yaml
    dir: ./k8s/cluster/dev

tasks:
  # Docs
  docs:install:
    cmds:
      - npm install --prune
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*

  docs:build:
    deps: [ docs:install ]
    cmds:
      - npm run build-docs
    sources:
      - acme-docs/decisions/**/*
      - acme-docs/handbook/**/*
      - acme-docs/root/**/*
      - acme-web/acme-web-server/docs/**/*
    generates:
      - acme-docs/build/**/*
