auth:
  usePasswordFiles: true
primary:
  persistence:
    size: 256Mi
  initdb:
    scripts:
      "init.sql": |-
        CREATE ROLE vault WITH LOGIN SUPERUSER PASSWORD 'rotate-me-immediately';
        CREATE ROLE keto_dba;
        CREATE ROLE keto_app;
        --
        CREATE DATABASE keto;
        ALTER DATABASE keto OWNER TO keto_dba;
        --
        \c keto;
        --
        REVOKE CREATE ON SCHEMA public FROM PUBLIC;
        GRANT CREATE ON SCHEMA public TO keto_dba;
        GRANT CREATE ON DATABASE keto TO keto_dba;
        --
        GRANT USAGE ON SCHEMA public TO keto_app;
        ALTER DEFAULT PRIVILEGES FOR ROLE keto_dba IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO keto_app;
        ALTER DEFAULT PRIVILEGES FOR ROLE keto_dba IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO keto_app;
