- id: "acme-web-server"
  upstream:
    url: "http://localhost:8080"
  match:
    url: "https://api-127-0-0-1.nip.io/<**>"
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
