---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: selenium-node-firefox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: selenium-node-firefox
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-firefox
          image: selenium/node-firefox:4.0
          ports:
            - containerPort: 5555
            - containerPort: 5900
            - containerPort: 7900
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_VNC_NO_PASSWORD
              value: "1"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: selenium-node-chrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: selenium-node-chrome
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:4.0
          ports:
            - containerPort: 5555
            - containerPort: 5900
            - containerPort: 7900
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_VNC_NO_PASSWORD
              value: "1"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: selenium-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.0
          ports:
            - containerPort: 4444
            - containerPort: 4443
            - containerPort: 4442
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-hub
spec:
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-hub
  ports:
    - port: 4444
      targetPort: 4444
      name: http
    - port: 4443
      targetPort: 4443
      name: port1
    - port: 4442
      targetPort: 4442
      name: port2
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-node-chrome
spec:
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-node-chrome
  ports:
    - port: 7900
      targetPort: 7900
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-firefox
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-node-firefox
spec:
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: selenium-node-firefox
  ports:
    - port: 7900
      targetPort: 7900

