version: v0.8.0-alpha.2

tracing:
  service_name: ory-keto
  provider: jaeger
  providers:
    jaeger:
      sampling:
        server_url: http://jaeger:5778
        type: const
        value: 1
      local_agent_address: jaeger-agent:6831

log:
  level: debug

namespaces:
  - id: 0
    name: scheduling

dsn: postgres://keto:keto@keto-postgres:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
  metrics:
    host: 0.0.0.0
    port: 4468
