receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  zpages: { }
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 683
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  #  loki:
  #    endpoint: "loki:3100"
  #    tls:
  #      insecure: true
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
service:
  extensions: [ zpages, memory_ballast ]
  pipelines:
    traces/1:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ jaeger ]
    metrics/1:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ prometheus ]
#    logs/1:
#      receivers: [ otlp ]
#      processors: [ memory_limiter, batch ]
#      exporters: [ loki ]

