apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "deployment-rotator.fullname" . }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: [{{ .Values.deployment | quote }}]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "deployment-rotator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "deployment-rotator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "deployment-rotator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}