---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-web-server
#  annotations:
#    sidecar.jaegertracing.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: acme-web-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: acme-web-server
      annotations:
#        linkerd.io/inject: enabled
#        prometheus.io/scrape: "true"
#        prometheus.io/port: "8080"
#        promtail.io/scrape: "true"
    spec:
      #      initContainers:
      #        - name: liquibase
      #          image: acme/acme-data-core
      #          imagePullPolicy: IfNotPresent
      #          args:
      #            - --classpath=/liquibase/changelog
      #            - --changeLogFile=changelog.yaml
      #            - --url=jdbc:postgresql://acme-web-server-postgres:5432/acme
      #            - --username=acme
      #            - --password=acme
      #            - --logLevel=debug
      #            - update
      #          envFrom:
      #            - secretRef:
      #                name: acme-web-server
      containers:
        - name: web-server
          image: acme/acme-web-server
          imagePullPolicy: IfNotPresent
#          env:
#            - name: JAEGER_AGENT_HOST
#              value: localhost
#            - name: JAEGER_SAMPLER_TYPE
#              value: "const"
#            - name: JAEGER_SAMPLER_PARAM
#              value: "1"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts: []
        - name: oathkeeper
          image: oryd/oathkeeper:v0.38
          imagePullPolicy: IfNotPresent
          args: ["serve", "proxy", "-c", "/etc/oathkeeper/oathkeeper.yml"]
          ports:
            - name: public
              containerPort: 4455
            - name: admin
              containerPort: 4456
          volumeMounts: []
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: acme-web-server
  labels:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: acme-web-server
spec:
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: acme-web-server
  ports:
    - port: 80
      targetPort: 4455
