apiVersion: batch/v1
kind: Job
metadata:
  name: keto-migrate
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: oryd/keto:v0.10.0-alpha.0
          imagePullPolicy: IfNotPresent
          args: [ "migrate", "up", "-y" ]
          volumeMounts: [ ]
      volumes: [ ]
