---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kratos-postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos
      app.kubernetes.io/component: postgres
  serviceName: kratos-postgres
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos
        app.kubernetes.io/component: postgres
      annotations:
        linkerd.io/inject: enabled
        promtail.io/scrape: "true"
    spec:
      containers:
        - name: postgres
          image: postgres:12.3-alpine
          env: [ ]
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresdata
  volumeClaimTemplates:
    - metadata:
        name: postgresdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-postgres
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: kratos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: kratos
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /admin/metrics/prometheus
        prometheus.io/port: "4434"
    spec:
      initContainers:
        - name: kratos-migrate
          image: oryd/kratos:v0.10.1
          imagePullPolicy: IfNotPresent
          args: [ "migrate", "sql", "-e", "--yes" ]
          volumeMounts:
            - name: kratos-common
              mountPath: /etc/kratos/common
      containers:
        - name: kratos
          image: oryd/kratos:v0.10.1
          imagePullPolicy: IfNotPresent
          args: [ "serve" ]
          envFrom: [ ]
          ports:
            - name: public
              containerPort: 4433
            - name: admin
              containerPort: 4434
          volumeMounts:
            - name: kratos-common
              mountPath: /etc/kratos/common
      volumes:
        - name: kratos-common
          configMap:
            name: kratos-common
---
apiVersion: v1
kind: Service
metadata:
  name: kratos
  labels:
    app.kubernetes.io/name: kratos
spec:
  ports:
    - name: public
      port: 4433
      targetPort: 4433
    - name: admin
      port: 4434
      targetPort: 4434
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: kratos

