apiVersion: batch/v1
kind: Job
metadata:
  name: kratos-migrate
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: oryd/kratos:v0.11.0
          imagePullPolicy: IfNotPresent
          args: [ "migrate", "sql", "-e", "--yes" ]
          volumeMounts: [ ]
      volumes: [ ]
