---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acme
      app.kubernetes.io/component: kratos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme
        app.kubernetes.io/component: kratos
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /admin/metrics/prometheus
        prometheus.io/port: "4434"
    spec:
      containers:
        - name: kratos
          image: oryd/kratos:v0.11.0
          imagePullPolicy: IfNotPresent
          args: [ "serve" ]
          envFrom: [ ]
          ports:
            - name: public
              containerPort: 4433
            - name: admin
              containerPort: 4434
          volumeMounts:
            - name: kratos-common
              mountPath: /etc/kratos/common
          livenessProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
            failureThreshold: 60
            successThreshold: 1
            periodSeconds: 1
            timeoutSeconds: 1
      volumes:
        - name: kratos-common
          configMap:
            name: kratos-common
---
apiVersion: v1
kind: Service
metadata:
  name: kratos
  labels:
    app.kubernetes.io/name: kratos
spec:
  ports:
    - name: public
      port: 4433
      targetPort: 4433
    - name: admin
      port: 4434
      targetPort: 4434
  selector:
    app.kubernetes.io/name: acme
    app.kubernetes.io/component: kratos

