apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: kratos-common
    files:
      - config/kratos/identity.schema.json
      - config/kratos/oidc.google.jsonnet

resources:
  - kratos.yml
  - kratos-migrate.yml
  - keto.yml
  - keto-migrate.yml
  - liquibase.yml
  - acme-web-server.yml
  - acme-app-web.yml
