# Default values for database-root-rotator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specifies the name of the Vault role to assume
vault:
  role: database-root-rotator
  addr: http://vault.management.svc.cluster.local:8200
  # Specifies the name of the Vault database connection to rotate
  database: ""

# Specifies when to rotate the password
schedule: "@weekly"

job:
  # Specifies if a job should be deployed to immediately rotate the password
  enabled: true
  ttlSecondsAfterFinished: 30
  activeDeadlineSeconds: 30
  backoffLimit:  3
  completions:  1
  parallelism:  1

image:
  repository: vault
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
