# NOTE:
# Unfortunately the environment variable approach to setting the CLIENT_ID and
# CLIENT_SECRET values as described by the Kratos docs does not work for OIDC
# providers. So here the full Google config is factored out into a separate
# config file, treated as a secret with Kubernetes and merged with the main
# configuration via an extra --config flag for Kratos.
# SEE: https://www.ory.sh/docs/ecosystem/configuring
# SEE: https://github.com/ory/kratos/discussions/1186
version: v0.10.1
selfservice:
  methods:
    oidc:
      config:
        providers:
          - id: google
            provider: google
            client_id: 113404764735-eosjn381028s0fiqqe652n0huihe2jon.apps.googleusercontent.com
            client_secret: z3PpLD1xd2XlrXtRfEcgHqH-
            mapper_url: file:///etc/kratos/common/oidc.google.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_0.name:
                  essential: true
                family_name: null
                # hd: null # If you want the G Suite domain
