= Deployment

The system can be run locally using a combination of {k3d-href}[k3d], {ingress-nginx-href}[ingress-nginx], and {skaffold-href}[Skaffold].
Run profiles are expressed in `skaffold.yml`.

== Local

The following is instructions on how to run the system locally on a development machine.

=== Prerequisites

==== Certificate Authority

A local certificate authority is managed using {mkcert-href}[mkcert].
Create and install the local certificate authority by running the following command:

[source, shell script]
----
$ mkcert -install
----

Restart your web browser for the local CA to be recognized.

==== Kubernetes Cluster

The local Kubernetes cluster is managed using {k3d-href}[k3d].
Ingress resources are managed with {ingress-nginx-href}[ingress-nginx].
A Gradle task creates and configures the cluster.
Run the following command from within the root project directory:

[source, shell script]
----
$ ./gradlew acme-ops:devStart
----

This will create the cluster and deploy the ingress-nginx service.

=== Profiles

==== Headless Profile

The "headless" profile runs only backend services.
Developers can then make use of first class dev tools installed locally, such as continuous compilation and hot-reload servers for user interfaces.
This profile is implemented as the default Skaffold profile.
Run the headless profile using the following command in the project's root directory:

[source, shell script]
----
$ skaffold run --tail
----

After a minute or two the system should converge on a healthy state.
If needed, check on the state of the pods by running the following command:

[source, shell script]
----
$ kubectl get pods
----

==== Local Profile

The "local" profile builds all container images and runs the whole system in a minimal fashion.
Run the local profile by running the following command from within the root project directory:

[source, shell script]
----
$ skaffold run --profile local
----

After a minute or two the system should converge on a healthy state.
Check on the state of the pods by running:

[source, shell script]
----
$ kubectl get pods
----

Once the pods are all running the web application should be accessible at https://app-127-0-0-1.nip.io/.

== Cloud
