= Quickstart

TIP: These instructions assume all tools mentioned in the xref:setup.adoc[Setup] section have been installed.

== Kotlin Modules

Run all Kotlin module tests by executing the following command from within the root directory:

[source,shell script]
----
$ ./gradlew test
----

Run one Kotlin module's tests by specifying the module name.
For example:

[source,shell script]
----
$ ./gradlew acme-web:acme-web-server:test
----

Run a subset of a module's tests by specifying a package or class name.
For example:

[source,shell script]
----
$ ./gradlew acme-web:acme-web-test:test --tests 'com.acme.web.test.*'
$ ./gradlew acme-web:acme-web-test:test --tests com.acme.web.test.scheduling.api.SchedulingClientCollectionApiSpec
----

== TypeScript Modules

Typescript module's tests can be executed by running `task test` from within the module's directory.
In most cases For example:

[source,shellscript]
----
$ cd acme-app/acme-app-web
$ task test
----

This will start a long-running process that re-runs tests when code is changed.
Press `Ctrl+C` to terminate the process.

== Run Locally

If desired, the system can be run locally on a {k3d-href}[k3d] cluster.
Run the following command from the root of the project:

[source,shellscript]
----
$ task run
----

This will start a long-running process that will redeploy services when code is changed.
Press `Ctrl+C` to terminate the process.
