= Quickstart

TIP: These instructions assume all tools mentioned in the xref:setup.adoc[Setup] section have been installed.

== Kotlin Modules

Run all Kotlin module tests by executing the following command from within the root directory:

[source,shell script]
----
$ ./gradlew test
----

Run one Kotlin module's tests by specifying the module name.
For example:

[source,shell script]
----
$ ./gradlew acme-web:acme-web-api:test
----

Run a subset of a module's tests by specifying a package or class name.
For example:

[source,shell script]
----
$ ./gradlew acme-web:acme-web-test:test --tests 'com.acme.web.test.*'
$ ./gradlew acme-web:acme-web-test:test --tests com.acme.web.test.scheduling.api.SchedulingClientCollectionApiSpec
----

== Run Locally

If desired, the system can be run locally on a local Kubernetes cluster.
Run the following command from the root of the project:

[source,shellscript]
----
$ task run
----

This will start a long-running process that will redeploy services when code is changed.
Press `Ctrl+C` to terminate the process.

If you'd rather avoid running `terraform` and the like before running locally, invoke `skaffold` manually:

[source,shellscript]
----
$ skaffold dev
----
