apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Prevents unnecessary updates to StatefulSets 'n such
  skaffold.dev/run-id: static
  app.kubernetes.io/managed-by: skaffold

configMapGenerator:
  - name: kratos-config
    files:
      - config/kratos/kratos.yml
  - name: keto-config
    files:
      - config/keto/keto.yml
  - name: acme-web-server-config
    files:
      - config/acme-web-server/application.conf
  - name: acme-web-server-oathkeeper-config
    files:
      - config/acme-web-server/access-rules.yml
      - config/acme-web-server/oathkeeper.yml

secretGenerator:
  - name: kratos-oidc-secrets
    files:
      - secrets/kratos/oidc.yml

bases:
  - ../../bases/acme

components:
  - ../../components/mailhog
  - ../../components/selenium-grid

resources:
  - ssl
  - ingress.yml

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: acme-web-server-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: acme
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: acme
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: acme
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: kratos-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: kratos
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: kratos
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: kratos
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: keto-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: keto
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: keto
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: keto
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kratos
    path: kratos.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: keto
    path: keto.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: acme-web-server
    path: acme-web-server.yml
