apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: wildcard-nip-io-tls
    type: "kubernetes.io/tls"
    files:
      - tls.crt=_wildcard.nip.io.pem
      - tls.key=_wildcard.nip.io-key.pem
