- path: /spec/template/spec/initContainers/0/args/0
  op: add
  value: --config
- path: /spec/template/spec/initContainers/0/args/1
  op: add
  value: /etc/keto/keto.yml
- path: /spec/template/spec/containers/0/args/0
  op: add
  value: --config
- path: /spec/template/spec/containers/0/args/1
  op: add
  value: /etc/keto/keto.yml
- path: /spec/template/spec/volumes/-
  op: add
  value:
    name: keto-config
    configMap:
      name: keto-config
- path: /spec/template/spec/containers/0/volumeMounts/-
  op: add
  value:
    mountPath: /etc/keto
    name: keto-config
- path: /spec/template/spec/initContainers/0/volumeMounts/-
  op: add
  value:
    mountPath: /etc/keto
    name: keto-config
