apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Prevents unnecessary updates to StatefulSets 'n such
  skaffold.dev/run-id: static
  app.kubernetes.io/managed-by: skaffold

configMapGenerator:
  - name: kratos-config
    files:
      - config/kratos/kratos.yml
  - name: keto-config
    files:
      - config/keto/keto.yml
  - name: acme-web-server-config
    files:
      - config/acme-web-server/application.conf
  - name: acme-web-server-oathkeeper-config
    files:
      - config/acme-web-server/access-rules.yml
      - config/acme-web-server/oathkeeper.yml

secretGenerator:
  - name: kratos-oidc-secrets
    files:
      - secrets/kratos/oidc.yml

bases:
  - ../../bases/acme

components:
  - ../../components/mailhog

resources:
  - ssl
  - ingress.yml

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: acme-web-server-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: acme
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: acme
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: acme
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: kratos-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: kratos
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: kratos
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: kratos
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: keto-postgres
    patch: |-
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_USER
          value: keto
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_PASSWORD
          value: keto
      - path: /spec/template/spec/containers/0/env/-
        op: add
        value:
          name: POSTGRES_DB
          value: keto
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kratos
    patch: |-
      - path: /spec/template/spec/initContainers/0/args/-
        op: add
        value: --config
      - path: /spec/template/spec/initContainers/0/args/-
        op: add
        value: /etc/kratos/kratos.yml
      - path: /spec/template/spec/containers/0/args/-
        op: add
        value: --config
      - path: /spec/template/spec/containers/0/args/-
        op: add
        value: /etc/kratos/kratos.yml
      - path: /spec/template/spec/containers/0/args/-
        op: add
        value: --config
      - path: /spec/template/spec/containers/0/args/-
        op: add
        value: /etc/kratos/oidc/oidc.yml
      - path: /spec/template/spec/containers/0/args/-
        op: add
        value: --watch-courier
      - path: /spec/template/spec/volumes/-
        op: add
        value:
          name: kratos-config
          configMap:
            name: kratos-config
      - path: /spec/template/spec/volumes/-
        op: add
        value:
          name: kratos-oidc-secrets
          secret:
            secretName: kratos-oidc-secrets
      - path: /spec/template/spec/containers/0/volumeMounts/-
        op: add
        value:
          mountPath: /etc/kratos
          name: kratos-config
      - path: /spec/template/spec/containers/0/volumeMounts/-
        op: add
        value:
          mountPath: /etc/kratos/oidc
          name: kratos-oidc-secrets
      - path: /spec/template/spec/initContainers/0/volumeMounts/-
        op: add
        value:
          mountPath: /etc/kratos
          name: kratos-config
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: keto
    patch: |-
      - path: /spec/template/spec/initContainers/0/args/0
        op: add
        value: --config
      - path: /spec/template/spec/initContainers/0/args/1
        op: add
        value: /etc/keto/keto.yml
      - path: /spec/template/spec/containers/0/args/0
        op: add
        value: --config
      - path: /spec/template/spec/containers/0/args/1
        op: add
        value: /etc/keto/keto.yml
      - path: /spec/template/spec/volumes/-
        op: add
        value:
          name: keto-config
          configMap:
            name: keto-config
      - path: /spec/template/spec/containers/0/volumeMounts/-
        op: add
        value:
          mountPath: /etc/keto
          name: keto-config
      - path: /spec/template/spec/initContainers/0/volumeMounts/-
        op: add
        value:
          mountPath: /etc/keto
          name: keto-config
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: acme-web-server
    patch: |-
      - path: /spec/template/spec/volumes/-
        op: add
        value:
          name: acme-web-server-config
          configMap:
            name: acme-web-server-config
      - path: /spec/template/spec/containers/0/volumeMounts/0
        op: add
        value:
          mountPath: /etc/acme/web
          name: acme-web-server-config
      - path: /spec/template/spec/volumes/-
        op: add
        value:
          name: acme-web-server-oathkeeper-config
          configMap:
            name: acme-web-server-oathkeeper-config
      - path: /spec/template/spec/containers/1/volumeMounts/0
        op: add
        value:
          mountPath: /etc/oathkeeper
          name: acme-web-server-oathkeeper-config
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: acme-app-web
    patch: |-
      - path: /spec/template/spec/containers/0/ports/0/containerPort
        op: replace
        value: 4200
  - target:
      version: v1
      kind: Service
      name: acme-app-web
    patch: |-
      - path: /spec/ports/0/targetPort
        op: replace
        value: 4200
