apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Prevents unnecessary updates to StatefulSets 'n such
  skaffold.dev/run-id: static
  app.kubernetes.io/managed-by: skaffold

bases:
  - ../local

patchesStrategicMerge:
  - delete-acme-app-web.yml

resources:
  - ingress.yml
