apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: otel-collector-config
    files:
      - config/otel-collector.yml
  - name: prometheus-config
    files:
      - config/prometheus.yml
resources:
  - otel-collector.yml
  - jaeger.yml
  - prometheus.yml
