adminPassword: admin

grafana.ini:
  server:
    domain: grafana-127-0-0-1.nip.io
    root_url: https://grafana-127-0-0-1.nip.io

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server
      isDefault: true
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3100
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        maxLines: 1000
      # jsonData:
      #   httpMethod: GET
      #   tracesToLogs:
      #     datasourceUid: 'loki'
      #     tags: ['job', 'instance', 'pod', 'namespace']
      #     mappedTags: [{ key: 'service.name', value: 'service' }]
      #     mapTagNamesEnabled: false
      #     spanStartTimeShift: '1h'
      #     spanEndTimeShift: '1h'
      #     filterByTraceID: false
      #     filterBySpanID: false
      #   tracesToMetrics:
      #     datasourceUid: 'prom'
      #     tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
      #     queries:
      #       - name: 'Sample query'
      #         query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
      #   serviceMap:
      #     datasourceUid: 'prometheus'
      #   search:
      #     hide: false
      #   nodeGraph:
      #     enabled: true
      #   lokiSearch:
      #     datasourceUid: 'loki'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  tls:
    - secretName: tls-io-nip-wildcard
      hosts:
        - grafana-127-0-0-1.nip.io
  hosts:
    - "grafana-127-0-0-1.nip.io"
  path: "/"