version: '3'

tasks:
  dev-create-cluster:
    cmds:
      - k3d cluster create acme-dev -p "80:80@loadbalancer" -p "443:443@loadbalancer" --k3s-arg "--disable=traefik@server:0"
    status:
      - k3d cluster list acme-dev
  dev-make-certs:
    dir: cluster/dev/001/.certs
    cmds:
      - mkcert '*.nip.io'
      - mkcert -install
    status:
      - ls _wildcard.nip.io*
  dev-fetch-secrets:
    env:
      OP_SECRET_ID: "tqq6mw5rylzps2t6ip7hlavnma"
    cmds:
      - ./cluster/dev/fetch-secrets.sh
  dev-provision:
    deps: [dev-create-cluster, dev-make-certs, dev-fetch-secrets]
    cmds:
      - terraform -chdir=cluster/dev/001 apply -auto-approve
      - terraform -chdir=cluster/dev/002 apply -auto-approve
  dev-destroy:
    cmds:
      - k3d cluster delete acme-dev
  dev-rebuild:
    cmds:
      - task: dev-destroy
      - task: dev-provision

