version: '3'

tasks:
  dev-create-cluster:
    cmds:
      - k3d cluster create acme-dev -p "80:80@loadbalancer" -p "443:443@loadbalancer" --k3s-arg "--disable=traefik@server:0"
    status:
      - k3d cluster list acme-dev
  dev-make-certs:
    dir: cluster/dev/001/.certs
    cmds:
      - mkcert '*.nip.io'
      - mkcert -install
    status:
      - ls _wildcard.nip.io*
  dev-fetch-secrets:
    env:
      OP_SECRET_ID: "tqq6mw5rylzps2t6ip7hlavnma"
    cmds:
      - ./cluster/dev/fetch-secrets.sh
  dev-provision-001-init:
    dir: cluster/dev/001
    cmds:
      - terraform init
    sources:
      - main.tf
    generates:
      - .terraform.lock.hcl
      - .terraform/**/*
  dev-provision-002-init:
    dir: cluster/dev/002
    cmds:
      - terraform init
    sources:
      - main.tf
    generates:
      - .terraform.lock.hcl
      - .terraform/**/*
  dev-provision-001:
    deps: [ dev-provision-001-init, dev-create-cluster, dev-make-certs, dev-fetch-secrets ]
    dir: cluster/dev/001
    cmds:
      - terraform apply -auto-approve
  dev-provision-002:
    deps: [ dev-provision-002-init, dev-provision-001 ]
    dir: cluster/dev/002
    cmds:
      - terraform apply -auto-approve
  dev-provision:
    cmds:
      - task: dev-provision-001
      - task: dev-provision-002
  dev-destroy:
    cmds:
      - k3d cluster delete acme-dev
  dev-rebuild:
    cmds:
      - task: dev-destroy
      - task: dev-provision

