name: Publish Antora Site
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-*
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
jobs:
  build:
    name: Publish
    uses: mattupstate/acme/.github/workflows/docs-build.yml@main
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site

