name: Build Antora Site
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-*
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
  workflow_call:
    
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - run: npm install
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npm run buildAntoraSite

