name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - acme-docs/**
      - acme-web/acme-web-api/docs/**
jobs:
  publish:
    name: Publish Antora Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: task docs:build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site

