name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test
