name: Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .idea/**
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
