name: Build Docs
on:
  pull_request:
    branches:
      - main
    paths:
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
jobs:
  build:
    name: Test Antora build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - run: task docs:build

