name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .idea/**
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .idea/**
      - acme-docs/**
      - acme-web/acme-web-server/docs/**
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: gradle/gradle-build-action@v2
        name: Collect Jacoco Reports
        with:
          arguments: mergeJacocoReports
      - uses: codecov/codecov-action@v3
        name: Report to Codecov
        with:
          files: ./build/reports/jacoco/xml/coverage.xml
