apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database-root-rotator.fullname" . }}-script
  labels:
    {{- include "database-root-rotator.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}

